# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3017f9792353ec3fe77852b0ff8880ea"
name = "product-health"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-10"

[[webhooks.subscriptions]]
topics = [ "products/create", "products/update", "products/delete" ]
uri = "/webhooks/products"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, read_products, read_inventory"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
